# name: Publish AutoReqGen Package to PyPI

# on:
#   push:
#     branches:
#       - main

# jobs:
#   pypi-publish:
#     name: Upload AutoReqGen release to PyPI
#     runs-on: ubuntu-latest
#     environment:
#       name: pypi
#       url: https://pypi.org/project/autoreqgen/

#     permissions:
#       id-token: write  # Required for trusted publishing

#     steps:
#       - name: Check if pushed by Harichselvam
#         run: |
#           echo "Committer email: ${{ github.event.head_commit.committer.email }}"
#           if [[ "${{ github.event.head_commit.committer.email }}" != "harichselvamc@gmail.com" ]]; then
#             echo "❌ Commit not by harichselvamc@gmail.com. Exiting CI/CD."
#             exit 1
#           fi

#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.x'

#       - name: Install build dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install setuptools wheel twine build

#       - name: Build package
#         run: |
#           python -m build

#       - name: Publish to PyPI
#         uses: pypa/gh-action-pypi-publish@release/v1
#         with:
#           user: __token__
#           password: ${{ secrets.PYPI_API_TOKEN }}
name: Publish AutoReqGen Package to PyPI and GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test on ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e .[dev]

      - name: Run tests
        run: |
          python -m unittest discover tests || true

  pypi-publish:
    name: Upload AutoReqGen release to PyPI and GitHub Packages
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/autoreqgen/

    permissions:
      id-token: write     # Required for PyPI Trusted Publishing
      packages: write     # Required for GitHub Packages

    steps:
      - name: Check if pushed by Harichselvam
        run: |
          echo "Committer email: ${{ github.event.head_commit.committer.email }}"
          if [[ "${{ github.event.head_commit.committer.email }}" != "harichselvamc@gmail.com" ]]; then
            echo "❌ Commit not by harichselvamc@gmail.com. Exiting CI/CD."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          pip install --upgrade pip
          pip install setuptools wheel build twine

      - name: Build package
        run: |
          python -m build

      - name: Publish to PyPI (via Trusted Publisher)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true

      - name: Publish to GitHub Packages
        run: |
          twine upload --repository-url https://upload.github.com/ dist/
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PACKAGE_TOKEN }}

      - name: Mention in GitHub Packages
        run: |
          echo "📝 This package is published to PyPI: https://pypi.org/project/autoreqgen/"
          echo "📦 This package is now also available via GitHub Packages:"
          echo "    https://github.com/${{ github.repository }}/packages"
