name: Publish AutoReqGen Package to PyPI

on:
  push:
    branches:
      - main

jobs:
  pypi-publish:
    name: Upload AutoReqGen release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/autoreqgen/

    permissions:
      id-token: write  # Required for trusted publishing

    steps:
      - name: Check if pushed by Harichselvam
        run: |
          echo "Committer email: ${{ github.event.head_commit.committer.email }}"
          if [[ "${{ github.event.head_commit.committer.email }}" != "harichselvamc@gmail.com" ]]; then
            echo "❌ Commit not by harichselvamc@gmail.com. Exiting CI/CD."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine build

      - name: Build package
        run: |
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
